/*

MIT License

Copyright (c) 2025 JustStudio. <https://juststudio.is-a.dev/>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

(()=>{
    "use strict";

    const JUSTC = {};
    JUSTC.Checks = {
        funcRegex: /^function\s*\w*\s*\(\)\s*\{\s*\[native code\]\s*\}$/,
        objRegex: /^\[object\s*\w*\]$/,
        sysFunc: (...functions) => {
            for (const func of functions) {
                if (typeof func != 'function' || !JUSTC.Checks.funcRegex.test(func+'')) throw new JUSTC.Error(JUSTC.Errors.environment);
            }
        },
        sysObj: (...objects) => {
            for (const obj of objects) {
                if (typeof obj != 'object' || !JUSTC.Checks.objRegex.test(obj+'')) throw new JUSTC.Error(JUSTC.Errors.environment);
            }
        }
    };

    const isAMD     =   typeof define === 'function' && define.amd;
    const isModule  = typeof module === 'object' && module.exports;
    const isBrowser =                          !isAMD && !isModule;

    if (!isBrowser && typeof require === 'function') {
        try {
            JUSTC.NodeWASM = require('./justc.node.js')
        } catch (_) {}
    }

    const globalThis_ = isBrowser ? []["filter"]["constructor"]("return globalThis")() || []["filter"]["constructor"]("return this")() || globalThis : globalThis || self || (isAMD ? {__justc__} : this) || {__justc__};
    if (!isBrowser) globalThis_.window = {};
    const OBJECT = Object;
    const json_ = JSON;
    const ARRAY = Array;
    const DOCUMENT = isBrowser ? document : null;
    const __URL__ = URL;
    const STRING = String;
    const ERR = Error;
    const CONSOLE = console;
    const MAP = Map;
    const BLOB = isBrowser ? Blob : null;
    const FETCH = fetch;
    const SCRIPT = isBrowser ? DOCUMENT.currentScript : null;
    const INT = parseInt;

    const isSafari = isBrowser ? /^((?!chrome|android).)*safari/i.test(globalThis_.navigator.userAgent) : false;
    if (isBrowser && !SCRIPT) throw new JUSTC.Error(JUSTC.Errors.environment);

    JUSTC.VERSION = null;
    JUSTC['+VERSION'] = null;
    JUSTC.GetVersion = function() {
        return JUSTC.VERSION === null ? false : (JUSTC.VERSION + (
            JUSTC['+VERSION'] === null || JUSTC['+VERSION'] === JUSTC.VERSION ? '' : (' ' + JUSTC['+VERSION'])
        ));
    };
    JUSTC.SetVersion = function(version) {
        if (!JUSTC.GetVersion()) JUSTC.VERSION = version;
    };
    JUSTC.Errors = {
        initWasm: 'JUSTC WebAssembly module hasn\'t been initialized yet.',
        wrongInputType: 'Argument 0 should be a string.',
        wasmFailed: 'Failed to initialize JUSTC WebAssembly module:',
        wasmInitFailed: 'Unable to initialize JUSTC WebAssembly module.',
        executionError: 'JUSTC/core/js.cpp error:',
        arrayInput: 'Array cannot be converted to JUSTC.',
        objectInput: 'Provided input is not valid object.',
        arg0: 'Invalid argument 0. Run "JUSTC = \'help\'" for help.',
        lexerError: 'JUSTC/core/lexer.cpp error: ',
        parseError: 'JUSTC/core/parser.cpp error: ',
        jsonInput: 'Argument 0 should be an object.',
        lexerInput: 'Provided input is not valid core.lexer output.',
        boolInput: 'Argument 1 should be a boolean.',
        environment: 'Invalid or compromised environment.',
        outputMode: 'Invalid output format.',
        version: (v) => `Cannot parse lexer tokens as the current JUSTC version is ${JUSTC.VERSION}, and the tokens appear to have been generated by the JUSTC lexer version ${v}.`,
        redefine: 'JUSTC cannot be redefined.',
        fetchWasm: 'Failed to fetch JUSTC WebAssembly module:',
    };

    if (isBrowser) {
        JUSTC.Checks.sysFunc(OBJECT, ARRAY, __URL__, STRING, ERR, MAP, BLOB, FETCH, INT);
        JUSTC.Checks.sysObj(json_, CONSOLE);
        JUSTC.Checks.sysObj(globalThis_, DOCUMENT);
        if (!isSafari) JUSTC.Checks.sysFunc(
            OBJECT.entries, OBJECT.defineProperty, OBJECT.freeze,
            json_.parse, json_.stringify,
            ARRAY.isArray, ARRAY.from,
            __URL__.parse,
            CONSOLE.log, CONSOLE.info, CONSOLE.error, CONSOLE.warn, CONSOLE.group, CONSOLE.groupEnd
        );
        JUSTC.Checks.sysFunc(DOCUMENT.createElement);
        JUSTC.Checks.sysObj(
            DOCUMENT.head,
            globalThis_.window
        );
        JUSTC.Checks.sysFunc(
            DOCUMENT.head.appendChild, DOCUMENT.head.removeChild
        );
    }

    JUSTC.JUSTC = undefined;
    JUSTC.Error = class extends ERR {};
    JUSTC.ErrorEnabled = true;
    JUSTC.CoreLogsEnabled = false;
    JUSTC.Silent = false;
    JUSTC.Experiments = false;

    if (!isBrowser && !JUSTC.JUSTC && !JUSTC.WASM && JUSTC.NodeWASM) {JUSTC.JUSTC = JUSTC.NodeWASM}
    else if (isBrowser && globalThis_.__justc__) throw new JUSTC.Error(JUSTC.Errors.environment);

    JUSTC.Console = function(type, ...args) {
        if (!JUSTC.Silent) {
            CONSOLE[type](...args);
        }
    };
    JUSTC.ErrorIfEnabled = function(...args) {
        if (JUSTC.ErrorEnabled) {
            throw new JUSTC.Error(...args);
        }
    };

    JUSTC.Core = {};
    JUSTC.CoreScript = function(code, name) {
        try {
            const resultptr = JUSTC.WASM.ccall(
                name,
                'number',
                ['string'],
                [code]
            );
            const resultjson = JUSTC.WASM.UTF8ToString(resultptr);
            JUSTC.WASM.ccall(
                'free_string',
                null,
                ['number'],
                [resultptr]
            );
            return json_.parse(resultjson);
        } catch (error) {
            throw new JUSTC.Error(JUSTC.Errors[name + 'Error'], error);
        }
    };
    JUSTC.Core.Lexer = function Lexer(code) {
        if (!JUSTC.WASM) throw new JUSTC.Error(JUSTC.Errors.initWasm);
        if (!code || typeof code != 'string' || code.length < 1) throw new JUSTC.Error(JUSTC.Errors.wrongInputType);
        const result = JUSTC.CoreScript(code, 'lexer');
        if (result.error) {
            throw new JUSTC.Error((result.lexer ? JUSTC.Errors.lexerError : (JUSTC.Errors.executionError + " ")) + result.error);
        } else {
            return result || {};
        }
    };
    JUSTC.Core.Parser = function Parser(code) {
        if (!JUSTC.WASM) throw new JUSTC.Error(JUSTC.Errors.initWasm);
        if (!code || typeof code != 'object') throw new JUSTC.Error(JUSTC.Errors.lexerInput);
        const result = JUSTC.CoreScript(json_.stringify(code), 'parser');
        if (result.error) {
            throw new JUSTC.Error((result.parser ? JUSTC.Errors.parseError : (JUSTC.Errors.executionError + " ")) + result.error);
        } else {
            return result.return || {};
        }
    };

    JUSTC.PrivateFunctions = {
        All: {
            Lexer: {
                NeedsWASM: true,
                Name: "core.lexer",
                Return: JUSTC.Core.Lexer
            },
            Parser: {
                NeedsWASM: true,
                Name: "core.parser",
                Return: function Parser(JavaScriptObjectNotation) {
                    if (typeof JavaScriptObjectNotation != 'object') throw new JUSTC.Error(JUSTC.Errors.jsonInput);
                    if (
                        typeof JavaScriptObjectNotation.input != 'string' ||
                        typeof JavaScriptObjectNotation.tokens != 'object' || !ARRAY.isArray(JavaScriptObjectNotation.tokens) ||
                        typeof JavaScriptObjectNotation.version != 'string'
                    ) throw new JUSTC.Error(JUSTC.Errors.lexerInput);
                    if (!JUSTC.GetVersion()) JUSTC.Public.version;
                    if (JavaScriptObjectNotation.version != JUSTC.VERSION && (()=>{
                        try {
                            const currVerInt = INT(STRING(JUSTC.VERSION).replaceAll('.',''), 10);
                            const inptVerInt = INT(STRING(JavaScriptObjectNotation.version).replaceAll('.',''), 10);
                            return currVerInt < inptVerInt;
                        } catch (_) {
                            return true
                        }
                    })()) throw new JUSTC.Error(JUSTC.Errors.version(JavaScriptObjectNotation.version));
                    for (const token of JavaScriptObjectNotation.tokens) {
                        if (typeof token != 'object' || token.type === undefined || token.start === undefined || typeof token.start != 'number' || token.value === undefined) throw new JUSTC.Error(JUSTC.Errors.lexerInput);
                    }
                    return JUSTC.Core.Parser(JavaScriptObjectNotation);
                }
            },
            CoreErrors: {
                NeedsWASM: false,
                Name: "errorsEnabled",
                Return: ()=>{return(JUSTC.ErrorEnabled)}
            },
            CoreLogs: {
                NeedsWASM: false,
                Name: "logsEnabled",
                Return: ()=>{return(JUSTC.CoreLogsEnabled)}
            },
            Silent: {
                NeedsWASM: false,
                Name: "isSilent",
                Return: ()=>{return(JUSTC.Silent)}
            },
            env: {
                NeedsWASM: false,
                Name: "detectedEnvironment",
                Return: ()=>{return(
                    isAMD ? 'AMD' : isModule ? 'Module/CommonJS' : isBrowser ? 'Browser' : 'unknown' + JUSTC.NodeWASM != undefined ? " (Node.js)" : ''
                )}
            }
        },
        Available: [
            'errorsEnabled',
            'logsEnabled',
            'isSilent',
            'detectedEnvironment'
        ],
        WhatToName: {
            "core.lexer": "Lexer",
            "core.parser": "Parser",
            "errorsEnabled": "CoreErrors",
            "logsEnabled": "CoreLogs",
            "isSilent": "Silent",
            "detectedEnvironment": "env"
        }
    };

    JUSTC.ScriptsAdded = [];
    JUSTC.Initialize = async function() {
        if (isBrowser) {
            try {
                const urlprefix = SCRIPT.src.slice(0,-8);
                JUSTC.FetchSource = async (path, _error) => {
                    if (JUSTC.CoreLogsEnabled) JUSTC.Console("log", "Fetching", path + "...");
                    return await(await FETCH(urlprefix + path).catch((error)=>{
                        JUSTC.Console("error", _error, typeof error === 'string' ? error : 'Failed to fetch.');
                    })).text();
                };
                const corewasmjs = await JUSTC.FetchSource('justc.core.js', JUSTC.Errors.fetchWasm);
                for (const src of [corewasmjs].filter(src => !JUSTC.ScriptsAdded.includes(src))) {
                    const script = DOCUMENT.createElement('script');
                    script.textContent = src;
                    script.type = 'text/javascript';
                    DOCUMENT.head.appendChild(script);
                    if (JUSTC.CoreLogsEnabled) JUSTC.Console("log", "Created script element in document.head.");
                    JUSTC.ScriptsAdded.push(src);
                }
                JUSTC.JUSTC = globalThis_.__justc__;
            } catch (error) {
                JUSTC.Console("error", JUSTC.Errors.fetchWasm, error);
            }
        }
        try {
            JUSTC.WASM = await JUSTC.JUSTC();
            if (JUSTC.CoreLogsEnabled) JUSTC.Console("log", "JUSTC WebAssembly module initialized.");
            JUSTC.JUSTC = null;
            delete JUSTC.JUSTC;
        } catch (error) {
            JUSTC.Console("error", JUSTC.Errors.wasmFailed, error);
        }
    };
    JUSTC.InitWASM = async function InitializeJUSTC(attempt = 0) {
        while (!JUSTC.WASM) {
            attempt++;
            await JUSTC.Initialize();
            if (attempt > 10) {
                throw new JUSTC.Error(JUSTC.Errors.wasmInitFailed);
            }
        };
        if (JUSTC.WASM) {
            for (const [unused, prfunc] of OBJECT.entries(JUSTC.PrivateFunctions.All)) {
                if (prfunc.NeedsWASM && !JUSTC.PrivateFunctions.Available.includes(prfunc.Name)) {
                    JUSTC.PrivateFunctions.Available.push(prfunc.Name);
                }
            }
        }
    };
    JUSTC.DisplayLogs = function(result) {
        if (result.logfile && result.logfile.file && result.logfile.file != '') {
            throw new JUSTC.Error("Logfile cannot be created in browser.");
        };
        if (result.logs && ARRAY.isArray(result.logs)) {
            result.logs.forEach(log => {
                if (log.type != 'ECHO') {
                    JUSTC.Console(
                        log.type == 'ERROR' ? 'error' : 'log',
                        `[JUSTC] (${log.time})`, log.message
                    );
                }
            });
        }
    };

    JUSTC.DefaultOutputMode = 'json';

    JUSTC.TryCatchLog = function(func, log) {
        try {
            return func()
        } catch (error) {
            CONSOLE.log(log);
            throw error
        }
    };

    JUSTC.Parse = function(code, execute = false, outputMode = JUSTC.DefaultOutputMode) {
        try {
            const resultPtr = JUSTC.WASM.ccall(
                'parse',
                'number',
                ['string', 'boolean', 'boolean', 'string'],
                [code, execute, false, outputMode]
            );

            const resultJson = JUSTC.WASM.UTF8ToString(resultPtr);
            JUSTC.WASM.ccall('free_string', null, ['number'], [resultPtr]);

            const result = JUSTC.TryCatchLog(()=>json_.parse(resultJson), resultJson);

            return result
        } catch (error) {
            CONSOLE.error(JUSTC.Errors.executionError, error);
            throw error;
        }
    };
    JUSTC.AsyncParse = async function(code, execute, outputMode = JUSTC.DefaultOutputMode) {
        return new Promise((resolve, reject) => {
            try {
                setTimeout(() => {
                    try {
                        const resultPtr = JUSTC.WASM.ccall(
                            'parse',
                            'number',
                            ['string', 'boolean', 'boolean', 'string'],
                            [code, execute, true, outputMode]
                        );

                        const resultJson = JUSTC.WASM.UTF8ToString(resultPtr);
                        JUSTC.WASM.ccall('free_string', null, ['number'], resultPtr);

                        const result = JUSTC.TryCatchLog(()=>json_.parse(resultJson), resultJson);

                        resolve(result)
                    } catch (error) {
                        console.error(JUSTC.Errors.executionError, error);
                        reject(new JUSTC.Error(JUSTC.Errors.executionError, error))
                    }
                }, 0)
            } catch (error) {
                reject(error)
            }
        })
    };

    JUSTC.CheckWASM = function() {
        if (!JUSTC.WASM) {
            throw new JUSTC.Error(JUSTC.Errors.initWasm);
        }
    };
    JUSTC.CheckInput = function(input) {
        if (!input || typeof input != 'string') {
            JUSTC.ErrorIfEnabled(STRING(input).length < 32 ? `"${STRING(input)}" is not valid JUSTC.` : ()=>{
                try {
                    if (!input.name) throw new JUSTC.Error('');
                    return `Provided ["${input.name}"] is not valid JUSTC.`;
                } catch (err) {
                    return "Provided code is not valid JUSTC.";
                }
            });
            return true;
        } else return false;
    };

    JUSTC.fromJSON = function(input) {
        if (ARRAY.isArray(input)) {
            throw new JUSTC.Error(JUSTC.Errors.arrayInput);
        } else {
            let output = '';
            for (const [name, value] of OBJECT.entries(json_.parse(json_.stringify(input)))) {
                output += (output.length > 0 ? ',' : '') + `${name}=${
                    typeof value === 'string' ? `"${value}"` :
                    value === true ? 'y' :
                    value === false ? 'n' :
                    value === null ? '' :
                    value
                }`;
            };
            return output + '.';
        }
    };

    JUSTC.OutputModes = [
        'json', 'xml', 'yaml'
    ];

    JUSTC.VFS = isBrowser ? class VirtualFileSystem {
        constructor() {
            this.files = new MAP();
        }

        createFile(filename, content, options = {}) {
            const {
                mimeType = 'text/plain',
                language = 'text',
                syntaxHighlighting = true
            } = options;

            this.files.set(filename, { content, mimeType, language });

            if (syntaxHighlighting) {
                this._registerFileInDevTools(filename, content, language);
            }

            return filename;
        }

        _registerFileInDevTools(filename, content, language) {
            const blob = new BLOB([content], { type: 'text/plain' });
            const url = __URL__.createObjectURL(blob);

            const script = DOCUMENT.createElement('script');
            script.textContent = `//# sourceMappingURL=data:application/json;base64,${btoa(json_.stringify({
                version: 3,
                file: filename,
                sources: [filename],
                sourcesContent: [content],
                mappings: ""
            }))}`;

            DOCUMENT.head.appendChild(script);
            DOCUMENT.head.removeChild(script);
            __URL__.revokeObjectURL(url);
        }

        getFile(filename) {
            return this.files.get(filename);
        }

        listFiles() {
            return ARRAY.from(this.files.keys());
        }
    } : undefined;
    JUSTC.CurrentVFS = isBrowser && !isSafari ? new JUSTC.VFS() : undefined;

    JUSTC.Check = (code) => {
        if (JUSTC.CheckInput(code)) throw new JUSTC.Error(JUSTC.Errors.wrongInputType);
        JUSTC.CheckWASM();
    };
    JUSTC.RunAsync = async (code, doExecute, ...args) => {
        JUSTC.Check(code);
        const result = await JUSTC.AsyncParse(code, doExecute, ...args);
        if (result.error) {
            throw new JUSTC.Error(result.error);
        } else {
            if (doExecute) JUSTC.DisplayLogs(result);
            return result.return || {};
        }
    };
    JUSTC.Taskify = (doExecute = false, outputMode = JUSTC.DefaultOutputMode, code) => {
        const tasks = [];
        for (const code_ of code) {
            tasks.push(async()=>{
                return await JUSTC.RunAsync(code_, doExecute, outputMode);
            });
        }
        return tasks
    };
    JUSTC.AsyncOutput = async function(bool, args) {
        let outputMode = JUSTC.DefaultOutputMode;
        let start = 0;
        let end = args.length;
        const lastArg = args[end - 1];
        if (JUSTC.OutputModes.includes(lastArg)) {
            outputMode = lastArg;
            end -= 1;
        } else if (JUSTC.OutputModes.includes(args[0])) {
            outputMode = args[0];
            start += 1;
        };
        return await Promise.all(await Promise.all(JUSTC.Taskify(bool, outputMode, args.slice(start, end))))
    };
    JUSTC.RegisterImports = function(imports) {
        if (isBrowser && !isSafari && imports && ARRAY.isArray(imports) && imports.length > 0) setTimeout(() => {
            try {
                for (const [url, content, type] of imports) {
                    JUSTC.CurrentVFS.createFile(url, content, {mimeType: type});
                }
            } catch (_) {}
        }, 0);
    };
    JUSTC.Output = {
        parse: isBrowser || !JUSTC.Experiments ? function(code, outputMode = JUSTC.DefaultOutputMode) {
            JUSTC.Check(code);
            if (!JUSTC.OutputModes.includes(outputMode)) throw new JUSTC.Error(JUSTC.Errors.outputMode);

            const result = JUSTC.Parse(code, false, outputMode);
            if (result.error) {
                throw new JUSTC.Error(result.error);
            } else {
                JUSTC.RegisterImports(result.imported);
                return result.return || {};
            }
        } : async function(...code) {
            return await JUSTC.AsyncOutput(false, code)
        },
        execute: isBrowser || !JUSTC.Experiments ? function(code, outputMode = JUSTC.DefaultOutputMode) {
            JUSTC.Check(code);
            if (!JUSTC.OutputModes.includes(outputMode)) throw new JUSTC.Error(JUSTC.Errors.outputMode);

            const result = JUSTC.Parse(code, true, outputMode);
            if (result.error) {
                throw new JUSTC.Error(result.error);
            } else {
                JUSTC.RegisterImports(result.imported);
                JUSTC.DisplayLogs(result);
                return result.return || {};
            }
        } : async function(...code) {
            return await JUSTC.AsyncOutput(true, code)
        },
        initialize: async function() {
            await JUSTC.InitWASM();
        },
        stringify: function(JavaScriptObjectNotation) {
            if (typeof JavaScriptObjectNotation != 'object') throw new JUSTC.Error(JUSTC.Errors.objectInput);
            return JUSTC.fromJSON(JavaScriptObjectNotation);
        },
        parseAsync: isBrowser && JUSTC.Experiments ? async function(...code) {
            return await JUSTC.AsyncOutput(false, code);
        } : undefined,
        executeAsync: isBrowser && JUSTC.Experiments ? async function(...code) {
            return await JUSTC.AsyncOutput(true, code);
        } : undefined,
    };
    JUSTC.Public = {
        get [Symbol.toStringTag]() {
            return 'JUSTC'
        },
        get ["version"]() {
            JUSTC.CheckWASM();
            const resultptr = JUSTC.WASM.ccall("version", "number");
            const result = JUSTC.WASM.UTF8ToString(resultptr);
            JUSTC.WASM.ccall(
                'free_string',
                null,
                ['number'],
                [resultptr]
            );
            if (!JUSTC.GetVersion()) {
                JUSTC.SetVersion(result);
            }
            return result
        }
    };
    for (const [name, value] of OBJECT.entries(JUSTC.Output)) {
        if (value != undefined) OBJECT.defineProperty(JUSTC.Public, name, {
            value,
            writable: false,
            configurable: false,
            enumerable: true
        });
    };
    JUSTC.Private = function(what) {
        if (!what || typeof what != 'string' || what.length < 1) throw new JUSTC.Error(JUSTC.Errors.arg0);
        if (JUSTC.PrivateFunctions.Available.includes(what)) {
            return JUSTC.PrivateFunctions.All[JUSTC.PrivateFunctions.WhatToName[what]].Return;
        } else {
            throw new JUSTC.Error(`JUSTC.requestPermissions: "${what}" is either not available or does not exist.`);
        }
    };
    JUSTC.HiddenOutput = {
        requestPermissions: function(what) {
            if (Array.isArray(what)) {
                const output = [];
                for (const item of what) {
                    output.push(JUSTC.Private(item));
                }
                return output
            }
            return JUSTC.Private(what);
        }
    };
    for (const [name, value] of OBJECT.entries(JUSTC.HiddenOutput)) {
        OBJECT.defineProperty(JUSTC.Public, name, {
            value,
            writable: false,
            configurable: false,
            enumerable: false
        })
    };

    JUSTC.CreateAsyncExports = function() {
        const exports = {};
        for (const [name, value] of OBJECT.entries(JUSTC.Output)) {
            exports[name] = async function(...args) {
                await JUSTC.InitWASM();
                return value.constructor.name === "AsyncFunction" ? await value(...args) : value(...args);
            };
        }
        for (const [name, value] of OBJECT.entries(JUSTC.HiddenOutput)) {
            OBJECT.defineProperty(exports, name, {
                value: async function(...args) {
                    await JUSTC.InitWASM();
                    return value.constructor.name === "AsyncFunction" ? await value(...args) : value(...args);
                },
                writable: false,
                configurable: false,
                enumerable: false
            });
        }
        OBJECT.defineProperty(exports, Symbol.toStringTag, {
            value: 'JUSTC',
            configurable: false
        });
        OBJECT.defineProperty(exports, "defineWASM", {
            value: function(WASMmodule) {
                if (!JUSTC.JUSTC) {
                    JUSTC.JUSTC = WASMmodule;
                }
            },
            writable: false,
            configurable: false,
            enumerable: false
        });

        return exports;
    };

    if (isBrowser) {
        if ("JUSTC" in globalThis_.window || "$JUSTC" in globalThis_.window) throw new JUSTC.Error(JUSTC.Errors.environment);
        OBJECT.defineProperty(globalThis_.window, 'JUSTC', {
            get: function() {
                JUSTC.InitWASM();
                return OBJECT.freeze(JUSTC.Public);
            },
            set: function(command) {
                if (typeof command === 'string' && command.length > 0) {
                    const vars = {
                        "version": "Public.version",
                        "core.lexer": "PrivateFunctions.All.Lexer.Return",
                        "core.parser": "PrivateFunctions.All.Parser.Return",
                        "detected.env": "PrivateFunctions.All.env.Return",
                        "options.silent": "Silent",
                        "core.errors": "ErrorEnabled",
                        "core.logs": "CoreLogsEnabled",
                        "options.experiments": "Experiments",
                        "options.defaultOutputMode": "DefaultOutputMode",
                    };
                    const types = {
                        "version": "string",
                        "options.silent": "boolean",
                        "options.core.errors": "boolean",
                        "options.core.logs": "boolean",
                        "options.experiments": "boolean",
                        "options.defaultOutputMode": "string",
                    };
                    const unredefinable = [
                        "version", "core.lexer", "core.parser", "detected.env"
                    ];
                    const bools = {
                        "true": true,
                        "yes": true,
                        "y": true,
                        "1": true,
                        "+": true,
                        "!0": true,
                        "false": false,
                        "no": false,
                        "n": false,
                        "0": false,
                        "-": false,
                        "!1": false,
                    };

                    const args = command.split(' ').filter(arg => arg);
                    function print(arg) {
                        CONSOLE.info(typeof JUSTC[vars[arg]] === 'function' ? JUSTC[vars[arg]]() : JUSTC[vars[arg]])
                    };
                    if (args.length == 1 && args[0] in vars) print(args[0]);
                    else {
                        switch (args[0]) {
                            case 'print':
                                if (args.length != 2 ||!(args[1]in vars)) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else print(args[1]);
                                break;
                            case 'set':
                                if (args.length != 3 ||!(args[1]in vars)||
                                    typeof JUSTC[vars[args[1]]]==='function' || (()=>{
                                        const varname = args[1];
                                        const vartype = types[varname];
                                        const set = args[2];
                                        switch (vartype) {
                                            case 'boolean':
                                                return!(set in bools);
                                            case 'string':
                                                return (varname === 'options.defaultOutputMode' && !JUSTC.OutputModes.includes(set));
                                            default:
                                                return false;
                                        }
                                    })() || unredefinable.includes(args[1])
                                ) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else if (types[args[1]] === 'boolean') {
                                    JUSTC[vars[args[1]]] = bools[args[2]];
                                } else {
                                    JUSTC[vars[args[1]]] = args[2];
                                }
                                break;
                            case 'switch':
                                if (args.length != 2 ||!(args[1]in vars||
                                    types[args[1]] != 'boolean'
                                )) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else {
                                    JUSTC[vars[args[1]]] = !JUSTC[vars[args[1]]];
                                }
                                break;
                            case 'enable':
                            case 'allow':
                                if (args.length != 2 ||!(args[1]in vars||
                                    types[args[1]] != 'boolean'
                                )) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else {
                                    JUSTC[vars[args[1]]] = true;
                                }
                                break;
                            case 'disable':
                            case 'disallow':
                                if (args.length != 2 ||!(args[1]in vars||
                                    types[args[1]] != 'boolean'
                                )) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else {
                                    JUSTC[vars[args[1]]] = false;
                                }
                                break;
                            case 'execute':
                            case 'parse':
                                if (args.length < 2) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else {
                                    CONSOLE.log(JUSTC.Output[args[0]](args.slice(1).join(' ')))
                                }
                                break;
                            case 'help':
                                CONSOLE.info('https://just.js.org/justc');
                                break;
                            case 'run':
                                if (args.length < 3 ||![
                                    'core.lexer',
                                    'core.parser'
                                ].includes(args[1])) JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                else {
                                    const func = args[1] === 'core.lexer' ? JUSTC.PrivateFunctions.All.Lexer.Return : JUSTC.PrivateFunctions.All.Parser.Return;
                                    CONSOLE.log(func(args.slice(2).join(' ')))
                                }
                                break;
                            default:
                                JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                                break;
                        }
                    }
                } else {
                    JUSTC.ErrorIfEnabled(JUSTC.Errors.redefine);
                }
            },
            configurable: false
        });
        OBJECT.defineProperty(globalThis_.window, '$JUSTC', {
            get: function() {
                return JUSTC.Output.execute;
            },
            set: function() {
                JUSTC.ErrorIfEnabled('$'+JUSTC.Errors.redefine);
            },
            configurable: false
        });
        if (!isSafari) setTimeout(async()=>{
            const RegisterSource = async function(url, vfs) {
                const text = await(await FETCH(url)).text();
                vfs.createFile(url, text, {
                    mimeType: url.endsWith('.cpp') ? 'text/x-c++src' :
                              url.endsWith('.hpp') ? 'text/x-c++hdr' :
                              url.endsWith('.h')   ? 'text/x-chdr'   :
                              'text/x-csrc'
                })
            };
            try {
                const urlprefix = SCRIPT.src.slice(0,-8)+'JUSTC/';
                const indexjson = await(await FETCH(urlprefix)).json();
                JUSTC['+VERSION'] = indexjson['version'][1] || null;
                const sources = indexjson['sources'];
                const CurrentVFS = new JUSTC.VFS();
                if (!ARRAY.isArray(sources)) return;
                for (const source of sources) {
                    if (typeof source != 'string') continue;
                    await RegisterSource(urlprefix+source, CurrentVFS);
                }
            } catch (_) {}
        },0);
    } else if (isModule) {
        module.exports = JUSTC.CreateAsyncExports()
    } else if (isAMD) {
        define(['require'], function(require) {
            return JUSTC.CreateAsyncExports()
        })
    } else {
        throw new JUSTC.Error('Unsupported environment.')
    }
})()
